version: "2"
run:
  tests: true
linters:
  default: none
  enable:
    # Bugs & correctness
    - govet           # Go vet checks
    - staticcheck     # Comprehensive static analysis
    - errcheck        # Unchecked errors
    - errorlint       # Error wrapping issues
    - bodyclose       # HTTP response body close
    - noctx           # HTTP requests without context
    - rowserrcheck    # SQL rows.Err() checks
    - sqlclosecheck   # SQL rows/statements close

    # Performance
    - prealloc        # Slice preallocation suggestions
    - unconvert       # Unnecessary type conversions

    # Style & maintainability
    - gocyclo         # Cyclomatic complexity
    - gocognit        # Cognitive complexity (different from cyclomatic)
    - funlen          # Function length limits
    - nestif          # Nested if statement depth
    - cyclop          # Package-level complexity analysis
    - ineffassign     # Ineffective assignments
    - unused          # Unused code detection
    - misspell        # Spelling mistakes
    - revive          # Fast, configurable linter (replaces golint)
    - gocritic        # Opinionated linter with many checks

    # Security (complements gosec)
    - gosec           # Security issues

  settings:
    gocyclo:
      min-complexity: 20  # Tightened from 25; DST algorithm excluded below
    gocognit:
      min-complexity: 35  # Cognitive complexity (spec.go:Next is 44, excluded)
    funlen:
      lines: 80           # Max function length (excluding comments/blank lines)
      statements: 50      # Max statements per function
    nestif:
      min-complexity: 4   # Max nested if depth
    cyclop:
      max-complexity: 15  # Package-level cyclomatic complexity
    misspell:
      locale: US
    staticcheck:
      checks:
        - all
        - -S1000  # Allow single-case select for readability
        - -S1037  # Allow select with timeout channel for test patterns
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
      disabled-checks:
        - hugeParam  # Too strict for this codebase
        - rangeValCopy  # Minor performance, reduces readability
        - builtinShadow  # min/max vars predate Go 1.21 builtins, code is clear
        - emptyStringTest  # len(s) == 0 is idiomatic in some contexts
    errcheck:
      check-type-assertions: true
      check-blank: false  # Allow explicit _ = err for intentional ignores
    gosec:
      excludes:
        - G104  # Audit errors not checked (too noisy for this codebase)
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gocyclo
          - gocognit
          - funlen     # Test functions are often long table-driven tests
          - cyclop     # Test complexity is expected
          - nestif     # Test conditionals are often complex
          - gocritic
          - prealloc   # Test setup often doesn't benefit from prealloc
          - gosec      # G115 int conversion in tests is safe
          - gci        # Test import order less critical
        path: _test\.go
      # Exclude inherently complex algorithms from complexity checks
      - linters:
          - gocyclo
          - gocognit
          - cyclop
          - funlen
        path: spec\.go
        source: "func.*Next"  # DST algorithm requires inherent complexity
      - linters:
          - gocyclo
          - gocognit
          - cyclop
        path: cron\.go
        source: "func.*run"   # Scheduler loop requires inherent complexity
      - linters:
          - gocyclo
          - cyclop
        path: parser\.go
        source: "func.*(getRange|normalizeFields|Parse|validateTimezone)"  # Parsing logic requires branching
      - linters:
          - nestif
        path: parser\.go  # Timezone parsing has legitimate nested conditionals
      - linters:
          - errcheck
        path: _test\.go
        text: "Error return value"  # Test files often ignore errors intentionally
      - linters:
          - revive
        text: "should omit type"  # Explicit types improve readability for public vars
      - linters:
          - revive
        path: _test\.go
        text: "time-naming"  # Test duration constants use descriptive names
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/netresearch/go-cron)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
