name: Auto-merge dependency PRs

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions: read-all

jobs:
  auto-merge:
    permissions:
      contents: write
      pull-requests: write
    uses: netresearch/.github/.github/workflows/auto-merge-deps.yml@eafa800ce23f3b52e0863ab042a8ba0801e97cab
