name: Dependency Review

on:
  pull_request:
    branches: [main]

permissions: read-all

jobs:
  dependency-review:
    name: Dependency Review
    permissions:
      contents: read
      pull-requests: write
    uses: netresearch/.github/.github/workflows/dependency-review.yml@eafa800ce23f3b52e0863ab042a8ba0801e97cab
    with:
      fail-on-severity: high
