name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  release:
    uses: netresearch/.github/.github/workflows/golib-create-release.yml@main
    permissions:
      contents: write
      id-token: write
      attestations: write
    with:
      draft: false
